version: "3.9"

services:
  db:
    container_name: postgresql
    image: postgres
    networks:
      - elastic
    ports:
      - 5432:5432
    volumes:
      - data01:/var/lib/postgresql/data
      - ./../db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Dubai
      - POSTGRES_DB=app_test
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
    restart: always
  web:
    image: crypto_ticker:latest
    ports:
      - 8010:8010
      - 8020:8020
    networks:
      - elastic
    environment:
      - TZ=Asia/Dubai
      - POSTGRES_NAME=app_test
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - DB_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.org
    restart: always
    depends_on:
      - db
  data_receiver:
    image: data_receiver_service:latest
    networks:
      - elastic
    environment:
      - TZ=Asia/Dubai
      - POSTGRES_NAME=app_test
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - DB_HOST=db
      - BINANCE_API_KEY=Q2hYHO2MgMrbOtfhqSwRs2lOHKkDHQvWP9bLY1Ndwu3IDygrUpef5csbsowfTcVs
      - BINANCE_API_SECRET=3fwhmOkjAADJVTfTx3xKyiivdTWhucGYMS4jIL1teAsIMtpG1RJ2MCAqgWEIQA6q
      - DATA_CAPTURING_INTERVAL=1
      - DATA_UPDATING_INTERVAL=5
    restart: always
    command:
      - /bin/sh
      - -c
      - sleep 1000
    depends_on:
      - db

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge